name: Push YAML to Another Repo

on:
  push:
    branches:
      - Devops 
    paths:
      - "argo/**/*.yaml"  # `argo` 폴더 내 YAML 파일 변경 시 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 A (현재 Repo) 체크아웃
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git 설정
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: 저장소 B (`mimiyaml.git`) 클론
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/05Daul/mimiyaml.git repo_b
          cd repo_b
          
          # 최신 변경 사항 가져오기 (브랜치가 없으면 생성)
          git fetch origin
          git checkout daul || git checkout -b daul
          git pull origin daul --rebase
          
          git config user.name "05Daul"
          git config user.email "elre519@naver.com"

      - name: YAML 파일 복사 및 푸시
        run: |
          # 저장소 A의 argo 폴더에 YAML 파일이 있는지 확인
          mkdir -p repo_b/argo  # 폴더가 없으면 생성
          cp -r argo/*.yaml repo_b/argo/ || echo "No YAML files to copy"

          # 저장소 B로 이동하여 변경 사항 커밋 및 푸시
          cd repo_b
          git add .
          if ! git diff --cached --exit-code; then
            git commit -m "자동 업데이트: 저장소 A에서 YAML 파일 변경됨"
            git push origin daul || (sleep 5 && git push origin daul)
          else
            echo "No changes detected, skipping push."
          fi
